In [2]:
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x.shape

(10,)

In [9]:
z = x.reshape((10,1))
z

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [10]:
z.shape

(10, 1)

In [7]:
np.squeeze(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
q = np.arange(30)[::-1]
q

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [16]:
q[[2,3,9]]

array([27, 26, 20])

In [19]:
z

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [18]:
z.reshape(10,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])