In [1]:
import tensorflow as tf

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [19]:
tf.reset_default_graph()
sess = tf.InteractiveSession()

* x: input image of shape [2, 3], 1 channel

In [20]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

x = tf.reshape(x, [1, 2, 3, 1])  # give a shape accepted by tf.nn.max_pool
print(x.shape)
x.eval()

(1, 2, 3, 1)


array([[[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]]], dtype=float32)

* valid_pad: max pool with 2x2 kernel, stride 2 and VALID padding.
* same_pad: max pool with 2x2 kernel, stride 2 and SAME padding (this is the classic way to go)
$$$$
`tf.nn.max_pool(value, ksize, strides, padding, data_format='NHWC')`
* NHWC = Num_samples x Height x Width x Channels

In [21]:
valid_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 2, 2, 1], padding='VALID')
valid_pad.get_shape() == [1, 1, 1, 1]  # valid_pad is [5.]
valid_pad.get_shape()

TensorShape([Dimension(1), Dimension(1), Dimension(1), Dimension(1)])

In [22]:
valid_pad.eval()

array([[[[5.]]]], dtype=float32)

In [23]:
same_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 2, 2, 1], padding='SAME')
same_pad.get_shape() == [1, 1, 2, 1]   # same_pad is  [5., 6.]
same_pad.get_shape()

TensorShape([Dimension(1), Dimension(1), Dimension(2), Dimension(1)])

In [24]:
same_pad.eval()

array([[[[5.],
         [6.]]]], dtype=float32)

In [17]:
sess.close()